apiVersion: v1
kind: Pod
metadata:
  name: restored-pod
spec:
  containers:
    - name: restored-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          cat /data/testfile.txt;
          sleep 3600;
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: restored-pvc
