name: Trivy vulnerability scanner
on:
  push: {}
  pull_request: {}
jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.16.1
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH